# Dockerfile-sadtalker
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel
ARG DEBIAN_FRONTEND=noninteractive

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y git tmux htop vim git-lfs pip wget openssl && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    wget \
    git \
    build-essential \
    libgl1 \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    libjpeg-dev \
    libpng-dev \
    unzip \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# RUN pip install -U flash-attn --no-build-isolation --use-pep517
RUN pip install --no-cache-dir  \
        -i https://pypi.tuna.tsinghua.edu.cn/simple  \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        torchaudio==2.1.2 \
        torchvision \
        numpy==1.23.4 \
        face_alignment==1.3.5 \
        imageio==2.19.3 \
        imageio-ffmpeg==0.4.7 \
        librosa==0.9.2 \
        numba \
        resampy==0.3.1 \
        pydub==0.25.1  \
        scipy==1.5.3 \
        kornia==0.6.8 \
        tqdm \
        yacs==0.1.8 \
        pyyaml  \
        joblib==1.1.0 \
        scikit-image==0.19.3 \
        av \
        # basicsr==1.4.1 \
        facexlib==0.3.0 \
        gradio>=4.0.0 \
        # gfpgan \
        safetensors \
        trimesh==3.9.20

# Install dlib
RUN pip install --no-cache-dir dlib-bin

# Install TTS manually (https://github.com/coqui-ai/TTS)
RUN pip install --no-cache-dir tts

WORKDIR /app
COPY . /app/

## Install GFPGAN
# RUN pip install git+https://github.com/TencentARC/GFPGAN
# RUN pip install --no-cache-dir gfpgan
RUN pip install --no-cache-dir /app/GFPGAN-master

RUN openssl req -x509 -days 3650 -nodes -newkey rsa  \
    -keyout ./key.pem -out ./cert.pem -subj "/CN=ChatTTS"

EXPOSE 7860

