# Dockerfile-sadtalker
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-devel
ARG DEBIAN_FRONTEND=noninteractive

# Install the timezone data package
RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
        apt-get install -y tzdata && \
        rm -rf /var/lib/apt/lists/*

# Set the timezone to Asia/Shanghai
ENV TZ=Asia/Shanghai
# Copy the local time file to the container
RUN cp /usr/share/zoneinfo/$TZ /etc/localtime \
        && echo $TZ > /etc/timezone

RUN apt-get update && DEBIAN_FRONTEND="noninteractive" \
    apt-get install -y git tmux htop vim git-lfs pip wget openssl && \
    rm -rf /var/lib/apt/lists/*

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common \
    wget \
    git \
    build-essential \
    libgl1 \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    libjpeg-dev \
    libpng-dev \
    unzip \
    ffmpeg && \
    rm -rf /var/lib/apt/lists/*

# RUN pip install -U flash-attn --no-build-isolation --use-pep517
RUN pip install --no-cache-dir  \
        -i https://pypi.tuna.tsinghua.edu.cn/simple  \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        torchaudio==2.1.2 \
        torchvision \
        numpy==1.23.4 \
        face_alignment \
        imageio \
        imageio-ffmpeg \
        librosa \
        numba \
        resampy \
        pydub  \
        scipy \
        kornia \
        tqdm \
        yacs \
        pyyaml  \
        joblib \
        scikit-image \
        basicsr==1.4.1 \
        facexlib \
        gradio \
        # gfpgan \
        safetensors \
        trimesh==3.9.20

# Install dlib
RUN pip install --no-cache-dir dlib-bin

# Install TTS manually (https://github.com/coqui-ai/TTS)
RUN pip install --no-cache-dir tts

WORKDIR /app
COPY . /app/

## Install GFPGAN
RUN pip install --no-cache-dir gfpgan

RUN openssl req -x509 -days 3650 -nodes -newkey rsa  \
    -keyout ./key.pem -out ./cert.pem -subj "/CN=ChatTTS"

EXPOSE 7860

